### ISSUE TITLE
Thanks for this docker image

### ISSUE THREAD

**Issue by samrocketman** [GameServerManagers/LinuxGSM-Docker#19]
I did this over the weekend and wanted to share with Linux GSM devs.   Thanks again for maintaining a docker image and making dedicated server management easy.

https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server

I'll close this issue tomorrow once some devs had a chance to see it.

**Comment by samrocketman** [comment]
Adding MIT license  to the project to match LGSM in case you want to take parts of it.

**Comment by h3o66** [comment]
Thanks, will have a look at this maybe for the next release.

**Comment by samrocketman** [comment]
Some code points of potential interest:

- [Customizing the Linux GSM docker image from within the docker-compose file](https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/67ff5c8993ad62a527c34924b177c5530e5d01ab/docker-compose.yml#L5-L49).
- [Random seed map generation for a value between 1 and 2147483647](https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/673dd757c4fa7f1ac0513cd2a5335466f1bc0ca0/utils/apply-settings.sh#L40).
- [Checking environment that environment variables are valid numbers and within a certain min/max range](https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/673dd757c4fa7f1ac0513cd2a5335466f1bc0ca0/utils/apply-settings.sh#L25-L32).  Returns non-zero function exit if the env var is  not a number or is a number but outside the range.
- [Randomly generate a password for RCON remote web console instead of the default value CHANGE_ME](https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/673dd757c4fa7f1ac0513cd2a5335466f1bc0ca0/utils/apply-settings.sh#L20-L22).
- [Self-hosted map support for custom maps by starting a basic web server on port 8000](https://github.com/samrocketman/docker-compose-lgsm-rust-dedicated-server/blob/673dd757c4fa7f1ac0513cd2a5335466f1bc0ca0/utils/apply-settings.sh#L64-L85) (uses `python -m SimpleHTTPServer &` to start the web server).
