### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by Ykzel** [GameServerManagers/LinuxGSM-Docker#22]
Hi everyone, first of all thanks for this work, I'm using LinuxGSM-Docker on an OMV server to host a Valheim server (great game!) and I have 2-3 technical questions.

First, I noticed that there is no "vi" or "nano" to edit my configuration files so I would like to install it but the account is not root... Could you please give me the root password so that I can make this addition and recreate an image for me?

Then there is something I don't understand. Why do I need to mount the next volume on my host when the "/home/lgsm" directory of the image is useless? 

-v /path/to/lgsm:/home/lgsm/

I wanted to mount "-v /path/to/lgsm:/home/linuxgsm" instead to have a direct access to the tree from my host machine but even by doing the "chown -R 750:750" on the associated directory I can't execute the ./vhserver command on my container anymore... What I don't miss or understand ?

Thank you!

**Comment by clairmont32** [comment]
Ditto the vi need for editing the configs. I'm playing with the volume issue too since I had the same thought of mounting a local folder with the config file. I'll report back if I figure it out.

**Comment by Ykzel** [comment]
> 
> 
> Ditto the vi need for editing the configs. I'm playing with the volume issue too since I had the same thought of mounting a local folder with the config file. I'll report back if I figure it out.

Thank you very much ! Could you also add the possibility to make cronjobs please ;)

**Comment by clairmont32** [comment]
Can you elaborate a bit more as to why you want/need cron in the container? Is the intent for server restarts?

**Comment by Ykzel** [comment]
Yes it's to be able to schedule backups, check for updates and restart.

**Comment by Ykzel** [comment]
> 
> 
> Can you elaborate a bit more as to why you want/need cron in the container? Is the intent for server restarts?

Yes it's to be able to schedule backups, check for updates and restart.

**Comment by clairmont32** [comment]
Sorry for the long reply. You can actually do this without needing cron inside the container. In a bit of research I had done some people say they have had issues with running more than 1 foreground process and it results in some container instability.

In the host's crontab you can put in docker exec <container name> <lgsm game binary command>. For example-
`docker exec valheim_server ./vhserver status`

If you want to get back into the container with an interactive shell you do `docker exec -ti <container name or ID> bash`
