### ISSUE TITLE
0x602 Network Error Ark is broke

### ISSUE THREAD

**Issue by Redstoneguy129** [GameServerManagers/LinuxGSM-Docker#58]
`Update state (0x11) preallocating, progress: 99.76 (17963936604 / 18006952591)
 Update state (0x11) preallocating, progress: 99.76 (17964478131 / 18006952591)
 Update state (0x11) preallocating, progress: 99.76 (17964525029 / 18006952591)
 Update state (0x11) preallocating, progress: 99.77 (17964668355 / 18006952591)
 Update state (0x11) preallocating, progress: 99.77 (17965413927 / 18006952591)
 Update state (0x201) stopping, progress: 0.00 (0 / 0)
Error! App '376030' state is 0x602 after update job.
Apr 21 19:30:37.502 arkserver: INSTALL: ERROR: Installing arkserver: SteamCMD: Update required but not completed - check network
Redirecting stderr to '/home/linuxgsm/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x11) preallocating, progress: 0.00 (0 / 18006952591)
 Update state (0x11) preallocating, progress: 1.31 (235266364 / 18006952591)
 Update state (0x11) preallocating, progress: 2.00 (360664529 / 18006952591)`
 
 As you can see i am following the install process then at the end of it the install fails and spits out a network error. I have run this 12 times. I am also using the default configuration. So either the latest ark is broke, the steam server is cutting out or you have shipped a buggy image. Everywhere online i see others have encountered same error except they didn't wait 2 hours of installing ark to encounter it. And no there are no permission problems.

**Comment by Claiyc** [comment]
Not an issue with lgsm, converting to discussion.
