### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by takov751** [GameServerManagers/LinuxGSM-Docker#61]
I was thinking while looking at the code. Would it be a more friendly construction to have a Linuxgsm docker with docker privileges and then each game server would be a separated docker managed by the main linuxgsm container . I perfectly understand that would be a fundamental change, which might not be ideal due it would me to rebase the whole project with different principals in mind . I was just interested in you contributors though

**Comment by jusito** [comment]
Probably this is the case if you provide complete configurable dockerimages and provide integration in panels like pterodactyl. So at least for me it looks like instead of implementing this here, adding support for integration into other projects who already solved this would solve your request?

**Comment by takov751** [comment]
It was just an conversation starter not a request. Nevertheless if the gameservers each would have their own docker image based on standard image and similar output and healthcheck, that would make it way easier to integrate with other solutions as you said. Ptherodactyl , portainer, yacht is just a few options to do management.
