### ISSUE TITLE
LGSM dockerized

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM-Docker#7]
Hey Ho,

I managed to run factorio, ark, 7D2D and arma3 within docker.
I saw that you started working on "dockerizing" lgsm. I have some experience with docker so far and would like to help.
Since I dont know how to contact you via Github, I do it by creating this issue.

What I did so far is to create an base-image and build docker container for each server on top of it. If you are interested I can share my work with you. 

Feel free to contact me =) I would like to help as much as I can!!

Best,
Avendretter

**Comment by JoaoAragaoVC** [comment]
Hello avendretter, I'm a bit new to this docker stuff. I'm using docker in unraid, with my TS3 Server, and now I would like to run in docker the LinuxGSM CS GO Server. My question is, have you ever managed to run a cs go server in Docker? I can run the pull commands, but i'm lost from there. 

Thanks in advance!
JoaoAragao

**Comment by ghost** [comment]
Hey JoaoAragao,

nope sorry didnt tried this yet.
Are u still interested?

Best,
Avendretter

**Comment by JoaoAragaoVC** [comment]
Hello again. I've managed to put it working! It is pretty easy after knowing it. 

Best regards,
João Aragão

**Comment by dgibbs64** [comment]
I recommend creating a PR of your work then I can be reviewed :)
